app:
  name: questionnaire
  url: http://127.0.0.1:3000 # This is the application (frontend) URL, not backend itself. Can be overrided by env
  httpPort: 9000 # This is the port backend server should listen to
  # httpsPort: 443 # This is the port backend server should listen to
  mode: dev
  log: log

database:
  driver: mysql # mysql, sqlite
  host: 127.0.0.1
  port: 3306
  database: questionnaire
  username: user01
  password: a1234567

admin:
  email:
    - admin@gmail.com
    - admin123@gmail.com

email:
  sender: inewsforpharm@gmail.com
  region: us-east-1
  numPerDay: 50000
  numPerSec: 14


jwt:
  secret: XXXX # For testing purpose. JWT should be stored in env
