export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const AUTH_STATUS = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
};

export const FORM_STATUS = {
  FETCH_FORMS_SUCCESS: 'FETCH_FORMS_SUCCESS',
  FETCH_FORMS_FAIL: 'FETCH_FORMS_FAIL',
};
